export const rollerFamilies = [
  {
    slug: 'contract-roller',
    name: 'Contract Roller',
    kicker: 'To be added',
    subtitle: 'The Contract Roller Collection brings together functionality, durability, and contemporary design in a versatile range of premium roller blind fabrics. From elegant translucent textures to sophisticated blackout and natural jute-inspired finishes, each design is crafted to enhance modern residential and commercial interiors. With a carefully curated palette of colors and patterns, this collection delivers exceptional light control, privacy, and timeless style.',
    room: 'TBD',
    light: 'TBD',
    texture: 'TBD',
    colors: ['#e2e2e2', '#d4d4d4', '#c6c6c6', '#b8b8b8'],
    image: '/assets/contract Roller.jpeg',
    catalog: '/catalogs/Contract Roller.pdf',
  },
  {
    slug: 'fc-1-and-2',
    name: 'FC 1 & 2',
    kicker: 'To be added',
    subtitle: 'Discover the FC1 & FC2 Exclusive Roller Blinds Collection, where innovative design meets timeless elegance. Crafted with premium fabrics, rich textures, and sophisticated patterns, this curated range transforms natural light into a statement of style while delivering exceptional privacy and functionality. From contemporary geometric weaves to luxurious designer finishes, every blind is designed to elevate modern homes, offices, hospitality spaces, and commercial interiors with effortless sophistication.',
    room: 'TBD',
    light: 'TBD',
    texture: 'TBD',
    colors: ['#e2e2e2', '#d4d4d4', '#c6c6c6', '#b8b8b8'],
    images: ['/assets/FC1.jpeg', '/assets/FC2.jpeg'],
    catalog: '/catalogs/FC1&2.pdf',
  },
  {
    slug: 'fc3',
    name: 'FC3',
    kicker: 'Designer Sheer Fabrics',
    subtitle: 'A curated collection of designer sheer fabrics that soften natural light with elegance and artistry. Featuring contemporary patterns and refined textures, Viento Sheers bring depth, warmth, and effortless sophistication to every space.',
    room: 'TBD',
    light: 'TBD',
    texture: 'TBD',
    colors: ['#e2e2e2', '#d4d4d4', '#c6c6c6', '#b8b8b8'],
  },
  {
    slug: 'fc4',
    name: 'FC4',
    kicker: 'Exclusive Blockout Collection',
    subtitle: 'Inspired by nature and contemporary design, the FC4 Collection features rich botanical patterns, sophisticated textures, and luxurious blockout fabrics. Designed for complete privacy and exceptional light control, it brings warmth, character, and elegance to modern living spaces.',
    room: 'TBD',
    light: 'TBD',
    texture: 'TBD',
    colors: ['#e2e2e2', '#d4d4d4', '#c6c6c6', '#b8b8b8'],
  },
  {
    slug: 'fc5',
    name: 'FC5',
    kicker: 'Exclusive Blockout Collection',
    subtitle: 'The FC5 Collection showcases premium designer fabrics with intricate patterns, refined weaves, and statement-making textures. Combining luxury aesthetics with superior blockout performance, it is crafted for interiors that demand both style and functionality.',
    room: 'TBD',
    light: 'TBD',
    texture: 'TBD',
    colors: ['#e2e2e2', '#d4d4d4', '#c6c6c6', '#b8b8b8'],
  },
  {
    slug: 'fc6',
    name: 'FC6',
    kicker: 'Viento Collection',
    subtitle: 'The FC6 Viento Collection embodies understated luxury with its rich woven textures, organic finishes, and timeless neutral palette. Designed to deliver complete privacy and exceptional light control, these premium blockout fabrics bring warmth, depth, and refined elegance to contemporary interiors. Perfect for homes, hospitality spaces, and modern commercial environments, FC6 combines performance with enduring style.',
    room: 'TBD',
    light: 'TBD',
    texture: 'TBD',
    colors: ['#e2e2e2', '#d4d4d4', '#c6c6c6', '#b8b8b8'],
  },
  {
    slug: 'customized-roller',
    name: 'Customized Roller',
    kicker: 'Colour-forward option',
    subtitle: 'Our Customized Roller Blinds are designed to bring together style, comfort, and functionality in one elegant window solution. Featuring premium fabrics, they offer effortless control over natural light and privacy. Available in a wide range of colors, textures, and exclusive patterns, each blind can be tailored to match your unique interior décor. Crafted from premium-quality materials, they ensure durability, smooth operation, and a sophisticated finish. Perfect for homes, offices, and commercial spaces, Viento Roller Blinds add a modern touch while enhancing the overall ambiance of any room.',
    room: 'Creative spaces',
    light: 'Dynamic accent',
    texture: 'Colour weave',
    colors: ['#d8e2dd', '#89aaa1', '#9d6f6f', '#355f58'],
    images: ['/assets/Customized zebra 1.png', '/assets/customized2.jpeg'],
    catalog: '/catalogs/CUSTOMIZED BLINDS .pdf',
  }
];
